[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
todo_dapp = "ExmLEjhb3xa2rj8wraPby9HBYJs34FJyS6MvgJoWX4fS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
